name: send-mail
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Whispers postman change
          to: chenkaic4233@gmail.com,747272975@qq.com
          from: Github Action
          body: ${{github.repository}} has change!
          attachments: README.md
